# This file is generated by setup.py. DO NOT EDIT!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

version = '1.10.0'
git_version = 'b080dab0d10ec3b46d5c343b90f70ca35a71e697'
